### ISSUE TITLE
Remaining Tasks Field Too Congested

### ISSUE THREAD

**Issue by angelamiranda11** [seaninigabriel15/SeaniniTask1-Simple_Todo_List#5]
![image](https://user-images.githubusercontent.com/14832233/93544162-f1c3c500-f98f-11ea-8898-e5310dcd0da5.png)

I suggest to make use of the white space around your `<div>`.
You can do two liner, sample: 
`Tasks: 6
Remaining tasks: 6` 

or 

do a one liner while making use of the space on the right, sample: 
`Tasks: 6`  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `Remaining Tasks: 6`

**Comment by seaninigabriel15** [comment]
Noted all this Maam :)

**Comment by angelamiranda11** [comment]
RESOLVED
